AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  collage-fe-stack

  SAM template for hosting a static website in S3.

Parameters:
  RootDomainName:
    Type: String
    Description: The DNS name of the website WITHOUT the www (e.g. 'complexnmr.com')

Resources:
  SiteCertificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: !Ref RootDomainName
        ValidationMethod: DNS
        DomainValidationOptions: 
          - DomainName: !Ref RootDomainName
            ValidationDomain: !Ref RootDomainName
        SubjectAlternativeNames:
          - !Sub 'www.${RootDomainName}'

Outputs:
  SiteCertificateARN:
    Description: "The ARN of the SSL certificate"
    Value: !Ref SiteCertificate
