AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  collage-fe-stack

  SAM template for hosting a static website in S3.

Parameters:
  RootDomainName:
    Type: String
    Description: The DNS name of the website WITHOUT the www (e.g. 'complexnmr.com'). This must also be the name of your bucket.
  HostedZoneId:
    Type: String
    Description: The ID of the Hosted Zone for the website in Route 53. Can be found in the AWS console.

Resources:
  SiteCertificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: !Ref RootDomainName
        ValidationMethod: DNS
        DomainValidationOptions: 
          - DomainName: !Ref RootDomainName
            ValidationDomain: !Ref RootDomainName
        SubjectAlternativeNames:
          - !Sub 'www.${RootDomainName}'

  SiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: 'index.html'
        Aliases:
          - !Ref RootDomainName
          - !Sub 'www.${RootDomainName}'
        Origins:
          - Id: S3Origin
            DomainName: !Sub '${RootDomainName}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref SiteCertificate
          SslSupportMethod: sni-only
  
  SiteRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref RootDomainName
          Type: A
          AliasTarget:
            DNSName: !GetAtt SiteCloudFront.DomainName
            HostedZoneId: Z2FDTNDATAQYW2 # Global CloudFront Hosted Zone ID
        - Name: !Sub 'www.${RootDomainName}'
          Type: A
          AliasTarget:
            DNSName: !GetAtt SiteCloudFront.DomainName
            HostedZoneId: Z2FDTNDATAQYW2 # Global CloudFront Hosted Zone ID

Outputs:
  SiteCertificateARN:
    Description: "The ARN of the SSL certificate for the frontend"
    Value: !Ref SiteCertificate
  CloudFrontDomainName:
    Description: "The domain name of the CloudFront distribution for the frontend"
    Value: !GetAtt SiteCloudFront.DomainName

  

